### ISSUE TITLE
Case sensitivity in QuantumDB and PostgreSQL

### ISSUE THREAD

**Issue by NGRichter** [quantumdb/quantumdb#63] opened 2021-05-14 10:31 UTC
In PostgreSQL, table and column names (I even think all names) without '"' (quotes) get automatically transformed to lowercase.
Oracle has the opposite (to uppercase), and I think MySQL does it another way.
I got the problem when using uppercase table and column names in a QuantumDB changeset that on a subsequent changeset QuantumDB could not migrate data from the old table to the next one due to the different names, e.g. "testtable" vs "TESTTABLE".

The problem is the quotes used in the SyncFunction and SelectiveMigratorFunction classes.

I had already tried to solve it by removing these quotes in the above classes and transforming every attribute in a changeset to lowercase except when quoted ( \&quot; ), but I think some more problems could arise when going this route. One thing is the generation of the sequence name -> "TestTable"_"TestColumn"_seq.

Before I make a pull request to solve this issue I want a discussion on how to solve it.

Does QuantumDB just lowercase every name except when quoted? 
e.g. tableName="TestTable" -> testtable
tableName="\&quot;TestTable\&quot;" -> TestTable
This is my preference as this is how PostgreSQL works

Or keep the name as is? tableName="TestTable" - > TestTable

**Comment by michaeldejong** [comment] 2021-05-15 17:18
Can you give me an actual reproduction for this issue? Because right now I'm not really sure what the problem is.

Since you're talking about table names I'm assuming that's the focus of the issue for you. But since quantumdb only creates tables named `table_<random_lowercase_identifier>`, that in itself can't be the issue. That makes me assume that you're initializing an existing database that contains tables with names that include uppercase characters. However when I try to init a simple database with a single table called "Users" I get the "Could not connect to the database." error message. But that's before we even get to classes like `SyncFunction`, and `SelectiveMigrationFunction`. That's definitely a bug, but it seems to be a different bug than what you're reporting here.

**Comment by NGRichter** [comment] 2021-05-17 07:11
I said tables, but I actually got the error when creating a table with uppercase column names, as column names do not change their name.

**Comment by michaeldejong** [comment] 2021-05-18 21:42
Getting a bit late now. Hoping to take a look a this tomorrow.

**Comment by michaeldejong** [comment] 2021-05-19 21:10
Think I found the issue. I have a solution for this, but it conflicts with your open PR. So let's get that merged first, and then I'll check the issue is still there, and if so rebase my changes.

**Comment by NGRichter** [comment] 2021-05-21 09:42
The problem right now is that the migration functions have quotes like NEW."ID" and OLD."ID" while the creation of tables and such have no quotes. 
QuantumDB should either have quotes everywhere or nowhere.
If we decide to have quotes everywhere than if a user defines a column as "Username" it will also stay with a capital U.
If we decide to remove the quotes everywhere than users have to put quotes in themselves for table and column creation but in QuantumDB some more checks and methods need to exist to check if  columns are uppercase and add the quotes back in.
I wrote this method earlier that is not yet included in a pull request to see if names should have quotes included, this would primarily be used in the CatalogLoader class where table and column names are retrieved from the database:
```
	private static String getQuotedString(String string) {
		if (!string.equals(string.toLowerCase())) {
			string = "\"" + string + "\"";
		}
		return string;
	}
```

**Comment by michaeldejong** [comment] 2021-05-21 20:11
> QuantumDB should either have quotes everywhere or nowhere.

It should probably use quotes everywhere.

> If we decide to have quotes everywhere than if a user defines a column as "Username" it will also stay with a capital U.

That seems reasonable. If someone adds this to their changelog:

```xml
<addColumn tableName="Users">
  <column name="Admin" type="boolean" defaultExpression="false" nullable="false" />
</addColumn>
```

Then I would expect a new column `Admin` to be added to the `Users` table. I can't imagine any developer deliberately using capital characters in changelogs, would then expect or rely on quantumdb (or a tool like Liquibase) to add a new column with a lowercased name just because it wasn't quoted. Additionally, should we ever start to support other databases (like Liquibase, etc), the changelog shouldn't have to change to get the same output (but for a different database). In other words let's avoid letting the database server alter the casing of table and column names, we should just be explicit in what we expect the database to do.

**Comment by michaeldejong** [comment] 2021-05-21 21:40
> Think I found the issue. I have a solution for this, but it conflicts with your open PR (#67). So let's get that merged first, and then I'll check that the issue is still there, and if so rebase my changes.

Your changed fixed part of the issue, but another bug popped up. I might have some time this weekend to dive into this.

**Comment by michaeldejong** [comment] 2021-05-24 17:39
I think with #70 merged into `master` we should now be able to run changelogs that use table and column names containing uppercase characters.

**Comment by michaeldejong** [comment] 2021-05-27 20:54
Closing this one for now. Please reopen if needed.

**Closed by michaeldejong** 2021-05-27 20:54 UTC
